homeassistant:
  name: Home
  latitude: !secret latitude
  longitude: !secret longitude
  elevation: !secret elevation
  unit_system: imperial
  time_zone: !secret time_zone

# Show links to resources in log and frontend
# introduction:

# Enables the frontend
frontend:

http:
  # Uncomment the following line to add a password (recommended!)
  api_password: !secret api_password
  # Uncomment the following line if you are using SSL or running in Docker etc
  # base_url: example.duckdns.org:8123
  # server_port: !secret port
  ssl_certificate: !secret ssl_cert
  ssl_key: !secret ssl_key
  
  # no password required for connections from these IP addresses
  trusted_networks:
    - 127.0.0.1 # loopback IP address (the Raspberry Pi itself)
    - 192.168.1.0/24  # Anything from 192.168.1.0 to 192.168.1.254 (i.e. anything on the local network)

# Checks for available updates
updater:

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
# This is currently restricted to a very limited "turn <Friendly Name> <on/off>" format, so I'm not going to bother with it
# conversation:

# Enables support for tracking state changes over time.
history:
  

# View all events in a logbook
logbook:
  exclude:
    domains:
      - sun

# Track the sun
sun:

# Nest thermostat
nest:
 client_id: !secret Nest_id
 client_secret: !secret Nest_secret
  
# IFTTT
ifttt:
  key: !secret maker_key

 
# Media (just Chromecast for now)
# media_player:
  # platform: cast

# Weather Prediction
sensor:
  - platform: yr

# Text to speech
tts:
  platform: google
  
# Notify to file
notify:
  - name: debug
    platform: file
    filename: debugNotify.txt
    timestamp: true

# Automation
automation: !include_dir_merge_list automation

# Inputs
input_boolean: !include inputs/input_boolean.yaml
input_slider: !include inputs/input_slider.yaml

# Creates a command to pull the latest updates from GitHub and then restart home assistant
shell_command:
  get_latest_config: bash /home/homeassistant/.homeassistant/fetchconfig.sh

script: !include_dir_merge_named script

# groups

group:

  # default_view:
    # view: yes
    # entities:
      # - group.home_nest
      # - group.home_advanced
      # - group.recipe_reader
      
  
  home_nest:
    name: Climate
    control: hidden
    entities:
      - climate.living_room
      - script.temporary_heat
      - script.temporary_cool
  
  home_advanced:
    name: Advanced
    control: hidden
    entities:
      - script.update_config
  
  
  debug_view:
    view: yes
    name: Debug
    entities:
      - group.debug_blinds
      - group.debug_nest
      - group.debug_misc
  
  
  debug_blinds:
    name: Blinds Simulation
    control: hidden
    entities:
      - input_boolean.tv_on
      - input_boolean.sun_debug
      - input_boolean.blinds_open
      - automation.close_blinds
      - automation.open_blinds
      
  debug_nest:
    name: Climate
    control: hidden
    entities:
      - input_slider.nest_temp
      - input_slider.nest_temp_lo
      - input_slider.nest_temp_hi
      - automation.nest_temp_change_trigger_value_template
      
  debug_misc:
    name: Misc
    control: hidden
    entities:
      - script.parse_command
      - automation.debug_delay
      - automation.time_checker
      - input_boolean.debug_bool
      - input_slider.debug
    



# python add ons
recipe_reader:


# temporarily removed as I prepare to update the Raspberry Pi

# hello_state:
# hello_service:


# simple_alarm:
  # known_light: input_boolean.tv_on
  # unknown_light: input_boolean.sun_debug
  
# simple_python:
  # input_bit: input_boolean.tv_on
  # output_bit: input_boolean.sun_debug