homeassistant:
  name: Home
  latitude: !secret latitude
  longitude: !secret longitude
  elevation: !secret elevation
  unit_system: imperial
  time_zone: !secret time_zone

# Show links to resources in log and frontend
# introduction:

# Enables the frontend
frontend:

http:
  # Uncomment the following line to add a password (recommended!)
   api_password: !secret api_password
  # Uncomment the following line if you are using SSL or running in Docker etc
  # base_url: example.duckdns.org:8123
  
  # no password required for connections from these IP addresses
  # trusted_networks:
    # - 127.0.0.1 # loopback IP address (the Raspberry Pi itself)
    # - 192.168.1.0/24  # Anything from 192.168.1.0 to 192.168.1.254 (anything on the local network)

# Checks for available updates
updater:

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time.
history:

# Let's try out this iframe thing
# panel_iframe:
 # router:
   # title: 'Router'
   # url: 'http://192.168.1.1'

# View all events in a logbook
logbook:
  exclude:
    domains:
      - sun

# Track the sun
sun:

# Nest thermostat
nest:
 client_id: !secret Nest_id
 client_secret: !secret Nest_secret
  
# IFTTT
ifttt:
  key: !secret maker_key

 
# Media (just Chromecast for now)
# media_player:
  # platform: cast

# Weather Prediction
sensor:
  - platform: yr

# Text to speech
tts:
  platform: google
  
# Notify to file
notify:
  - name: debug
    platform: file
    filename: debugNotify.txt
    timestamp: true

# Automation
automation: !include_dir_merge_list automation

# Inputs
input_boolean: !include inputs/input_boolean.yaml
input_slider: !include inputs/input_slider.yaml

# Creates a command to pull the latest updates from GitHub and then restart home assistant
shell_command:
  get_latest_config: bash /home/homeassistant/.homeassistant/pullconfig.sh

script: !include_dir_merge_named script
