#------------------------------------------------------------------------------------#
#   A script to update the home assistant configuration by fetching from github      #
#                                                                                    #
#   Fetch the latest files from github, then restart home assistant.                 #
#------------------------------------------------------------------------------------#


  update_config:
    sequence:
      - service: shell_command.get_latest_config
      - service: homeassistant.restart